### ISSUE TITLE
What causes the following error?

### ISSUE THREAD

**Issue by deathcrafter** [khanhas/PowershellRM#3]
System.Management.Automation.PSInvalidOperationException: The pipeline was not run because a pipeline is already running. Pipelines cannot be run concurrently.
   at System.Management.Automation.Runspaces.PipelineBase.DoConcurrentCheck(Boolean syncCall, Object syncObject, Boolean isInLock)
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndAddToRunningPipelines(PipelineBase pipeline, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumer (ASimpleVisualizer2\settings\settings.ini - [Crafter])

**Comment by khanhas** [comment]
At least give code you are trying to run.
Anyway, try restart Rainmeter first.

**Comment by deathcrafter** [comment]
> 
> 
> At least give code you are trying to run.
> Anyway, try restart Rainmeter first.

Actually it's a whole script. You can find it [here](https://github.com/deathcrafter/ASimpleVisualizer2/blob/master/%40Resources/Scripts/Crafter.ps1). 

And I execute required commands with OnRefreshAction. This error appears when I refresh the skin from another skin. When refreshed from within the skin it works fine. Restarting Rainmeter doesn't help.
